import {currentMatchup} from './game-bridge.js';
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const innings=game=>Math.max(game.lineScore.away.length,game.lineScore.home.length);
const lineScore=game=>`<div class="tablewrap"><table><thead><tr><th class="name">TEAM</th>${Array.from({length:innings(game)},(_,i)=>`<th>${i+1}</th>`).join('')}<th>R</th><th>H</th><th>E</th></tr></thead><tbody>${['away','home'].map(side=>`<tr><td class="name">${esc(game.teams[side].name)}</td>${Array.from({length:innings(game)},(_,i)=>`<td>${game.lineScore[side][i]??'—'}</td>`).join('')}<td class="ratingpill">${game.score[side]}</td><td>${game.hits[side]}</td><td>${game.errors[side]}</td></tr>`).join('')}</tbody></table></div>`;
const batterRows=(game,side)=>{const ids=new Map([...game.teams[side].lineup.map(e=>e.player),...game.teams[side].bench].map(p=>[p.id,p.name]));return Object.entries(game.battingStats).filter(([id])=>ids.has(id)).map(([id,s])=>`<tr><td class="name">${esc(ids.get(id))}</td><td>${s.ab}</td><td>${s.h}</td><td>${s.hr}</td><td>${s.rbi}</td><td>${s.bb}</td><td>${s.so}</td></tr>`).join('');};
const pitcherRows=(game,side)=>{const names=new Map(game.teams[side].pitchers.map(p=>[p.id,p.name]));return Object.entries(game.pitchingStats).filter(([id])=>names.has(id)).map(([id,s])=>`<tr><td class="name">${esc(names.get(id))}</td><td>${Math.floor(s.outs/3)}.${s.outs%3}</td><td>${s.pitches}</td><td>${s.hitsAllowed}</td><td>${s.walks}</td><td>${s.strikeouts}</td><td>${s.earnedRuns}</td></tr>`).join('');};
export function gameMarkup(game){
  const live=game.status==='playing',match=live?currentMatchup(game):null;
  return `<div class="modalscore"><span>${esc(game.teams.away.name)} &nbsp; vs &nbsp; ${esc(game.teams.home.name)}</span><strong>${game.score.away} : ${game.score.home}</strong><span class="tag">${live?`${game.inning}회 ${game.half==='top'?'초':'말'} · ${game.outs}아웃 · ${game.count.balls}B ${game.count.strikes}S`:'경기 종료'}</span></div>${lineScore(game)}${live?`<div class="note" style="margin-top:16px">타자 <b>${esc(match.batter.name)}</b> · 투수 <b>${esc(match.pitcher.name)}</b> ${match.pitcher.pitchCount}구<br>${esc(game.lastPlay)}</div><div class="modalactions"><button class="secondary" data-engine="pitch">1구 진행</button><button class="secondary" data-engine="half">반 이닝 자동</button><button class="primary" data-engine="game">경기 끝까지 자동</button></div>`:`<div class="modalactions"><button class="primary" data-engine="close">결과 확인 완료</button></div>`}<details style="margin-top:20px"><summary>상세 박스스코어</summary>${['away','home'].map(side=>`<h3 style="margin:20px 0 10px">${esc(game.teams[side].name)} · 타자</h3><div class="tablewrap"><table><thead><tr><th class="name">선수</th><th>AB</th><th>H</th><th>HR</th><th>RBI</th><th>BB</th><th>K</th></tr></thead><tbody>${batterRows(game,side)}</tbody></table></div><h3 style="margin:20px 0 10px">${esc(game.teams[side].name)} · 투수</h3><div class="tablewrap"><table><thead><tr><th class="name">선수</th><th>IP</th><th>NP</th><th>H</th><th>BB</th><th>K</th><th>ER</th></tr></thead><tbody>${pitcherRows(game,side)}</tbody></table></div>`).join('')}</details>`;
}
