import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,positions,movePlayer,assignField,reorder,swap,assignPitcher,schedule} from '../model.js';
function valid(s){const ids=Object.values(s.field).filter(Boolean);assert.equal(new Set(ids).size,ids.length);assert.deepEqual([...ids].sort(),[...s.order].sort());for(const id of [...ids,...s.rotation,...s.bullpen])assert.equal(s.players.find(p=>p.id===id).group,'first');assert.equal(new Set([...s.rotation,...s.bullpen]).size,s.rotation.length+s.bullpen.length);}
const bench=s=>s.players.find(p=>p.group==='first'&&!p.pitcher&&!s.order.includes(p.id)).id,farm=s=>s.players.find(p=>p.group==='second'&&!p.pitcher).id;
test('demotion removes a starter from field and order, promotion does not silently reassign',()=>{const s=initialState(),cf=s.field.CF;movePlayer(s,cf,'second');assert.equal(s.field.CF,null);assert.equal(s.order.length,8);movePlayer(s,cf,'first');assert.equal(s.order.length,8);assignField(s,cf,'CF');valid(s);});
test('bench replacement keeps nine unique players; starters exchange defensive positions',()=>{const s=initialState(),cf=s.field.CF,second=s.field['2B'],slot=s.order.indexOf(cf),b=bench(s);assignField(s,b,'CF');assert.equal(s.order[slot],b);assert.ok(!s.order.includes(cf));assignField(s,second,'CF');assert.equal(s.field['2B'],b);valid(s);});
test('pitcher and non-first-team player cannot enter batting lineup',()=>{const s=initialState();assert.equal(assignField(s,s.rotation[0],'C'),false);assert.equal(assignField(s,farm(s),'C'),false);valid(s);});
test('injured list clears pitcher assignment and returning pitcher enters bullpen',()=>{const s=initialState(),sp=s.rotation[0];movePlayer(s,sp,'injured');assert.ok(!s.rotation.includes(sp));movePlayer(s,sp,'first');assert.ok(s.bullpen.includes(sp));valid(s);});
test('cross-group pitching drag exchanges jobs and within-group drag reorders',()=>{const s=initialState(),sp=s.rotation[0],rp=s.bullpen[0];assignPitcher(s,rp,'rotation',sp);assert.equal(s.rotation[0],rp);assert.equal(s.bullpen[0],sp);assignPitcher(s,rp,'rotation',s.rotation[4]);assert.equal(s.rotation[4],rp);valid(s);});
test('batting reorder handles both directions without duplication',()=>{const s=initialState(),[a,b]=s.order,z=s.order[8];reorder(s.order,a,z);assert.equal(s.order[8],a);reorder(s.order,a,b);assert.equal(s.order[0],a);valid(s);});
test('batting order swap exchanges two slots without shifting other players',()=>{const s=initialState(),original=[...s.order],a=original[0],z=original[8];swap(s.order,a,z);assert.equal(s.order[0],z);assert.equal(s.order[8],a);assert.deepEqual(s.order.slice(1,8),original.slice(1,8));valid(s);});
test('schedule has correct month length and no results before opening day',()=>{assert.equal(schedule(2).length,28);assert.equal(schedule(6).length,30);assert.equal(schedule(7).length,31);for(const g of schedule(6)){assert.equal(g.a,g.ours.reduce((a,b)=>a+b,0));assert.equal(g.b,g.theirs.reduce((a,b)=>a+b,0));assert.equal(g.done,false);}});
