import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,positions,movePlayer,assignField,reorder,swap,assignPitcher,schedule} from '../model.js';
function valid(s){const ids=Object.values(s.field).filter(Boolean);assert.equal(new Set(ids).size,ids.length);assert.deepEqual([...ids].sort(),[...s.order].sort());for(const id of [...ids,...s.rotation,...s.bullpen])assert.equal(s.players.find(p=>p.id===id).group,'first');assert.equal(new Set([...s.rotation,...s.bullpen]).size,s.rotation.length+s.bullpen.length);}
test('demotion removes a starter from field and order, promotion does not silently reassign',()=>{const s=initialState();movePlayer(s,'0-0','second');assert.equal(s.field.CF,null);assert.equal(s.order.length,8);movePlayer(s,'0-0','first');assert.equal(s.order.length,8);assignField(s,'0-0','CF');valid(s);});
test('bench replacement keeps nine unique players; starters exchange defensive positions',()=>{const s=initialState();assignField(s,'0-9','CF');assert.equal(s.order[0],'0-9');assert.ok(!s.order.includes('0-0'));assignField(s,'0-1','CF');assert.equal(s.field['2B'],'0-9');valid(s);});
test('pitcher and non-first-team player cannot enter batting lineup',()=>{const s=initialState();assert.equal(assignField(s,'0-15','C'),false);assert.equal(assignField(s,'0-32','C'),false);valid(s);});
test('injured list clears pitcher assignment and returning pitcher enters bullpen',()=>{const s=initialState();movePlayer(s,'0-15','injured');assert.ok(!s.rotation.includes('0-15'));movePlayer(s,'0-15','first');assert.ok(s.bullpen.includes('0-15'));valid(s);});
test('cross-group pitching drag exchanges jobs and within-group drag reorders',()=>{const s=initialState();assignPitcher(s,'0-20','rotation','0-15');assert.equal(s.rotation[0],'0-20');assert.equal(s.bullpen[0],'0-15');assignPitcher(s,'0-20','rotation','0-19');assert.equal(s.rotation[4],'0-20');valid(s);});
test('batting reorder handles both directions without duplication',()=>{const s=initialState();reorder(s.order,'0-0','0-8');assert.equal(s.order[8],'0-0');reorder(s.order,'0-0','0-1');assert.equal(s.order[0],'0-0');valid(s);});
test('batting order swap exchanges two slots without shifting other players',()=>{const s=initialState(),original=[...s.order];swap(s.order,'0-0','0-8');assert.equal(s.order[0],'0-8');assert.equal(s.order[8],'0-0');assert.deepEqual(s.order.slice(1,8),original.slice(1,8));valid(s);});
test('schedule has correct month length and box score totals',()=>{assert.equal(schedule(2).length,28);assert.equal(schedule(6).length,30);assert.equal(schedule(7).length,31);for(const g of schedule(6)){assert.equal(g.a,g.ours.reduce((a,b)=>a+b,0));assert.equal(g.b,g.theirs.reduce((a,b)=>a+b,0));}assert.equal(schedule(6)[13].done,false);assert.equal(schedule(5)[13].done,true);});
